version: 2.1

jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout # git clone <my repo>
      - run:
          name: "Build the service"
          command: |
            echo "Hello this is build step"
            ls
            pwd
            cat README.md

  test:
    docker:
      - image: alpine
    steps:
      - run:
          name: "Test step"
          command: |
            echo "Hello this is test step"
workflows:
  welcome:
    jobs:
      - build
      - test:
          requires:
            - build